(in-package #:nervous-island.tilemaker.shapes)

(defun net (&optional (side *side*))
  (v:with-graphics-state
    (v:translate 0 (* 0.32 side))
    ;; Clip path
    (let ((x (* 0.5 side)))
      (v:move-to x (* 1 x))
      (v:line-to (* -1 x) (* 1 x))
      (v:line-to (* -1 x) (* -1 x))
      (v:line-to x (* -1 x))
      (v:line-to x (* 1 x))
      (v:clip-path)
      (v:end-path-no-op))
    (v:rotate (* pi 1/4))
    (labels ((make-lines (offset)
               (dotimes (i 9)
                 (let ((start (+ (* 0.1 side) (* 0.05 side (- i 1.5)))))
                   ;; One direction
                   (v:move-to (+ start offset) (- offset))
                   (v:line-to (+ start offset) (+ (* 0.5 side) offset))
                   (v:line-to (- start offset) (+ (* 0.5 side) offset))
                   (v:line-to (- start offset) (- offset))
                   (v:line-to (+ start offset) (- offset))
                   (v:fill-path)
                   ;; The other direction
                   (v:move-to (- offset) (+ start offset))
                   (v:line-to (+ (* 0.5 side) offset) (+ start offset))
                   (v:line-to (+ (* 0.5 side) offset) (- start offset))
                   (v:line-to (- offset) (- start offset))
                   (v:line-to (- offset) (+ start offset))
                   (v:fill-path)))))
      (v:scale 1.4 1.4)
      (v:set-rgba-fill 1 1 1 1)
      (make-lines (* 0.014 side))
      (v:set-rgba-fill 0 0 0 1)
      (make-lines (* 0.006 side)))))
